### 1. CREAR UN ALUMNO
POST http://localhost:3000/alumno
Content-Type: application/json

{
  "nif": "12345678C",
  "nombre": "Carmen",
  "apellido1": "Fernandez",
  "apellido2": "Fernandez",
  "grupo": "2º ASIR"
}

### 2. CREAR UNA PRÁCTICA
POST http://localhost:3000/practica
Content-Type: application/json

{
  "titulo": "Revision de Servidores",
  "dificultad": "Baja"
}

### 3. REGISTRAR UNA NOTA (EVALUACIÓN)
# Aquí unimos al Alumno (ID 1) con la Práctica (ID 1)
POST http://localhost:3000/evaluacion/practica
Content-Type: application/json

{
  "alumnoId": 3,
  "practicaId": 3,
  "fecha": "2026-03-22",
  "nota": 9.5
}

### 4. VER LOS RESULTADOS CON LAS RELACIONES
GET http://localhost:3000/evaluacion/practicas